planname="test12";sumofcases=1;planedtime=1356360273.04;planstarttime=1356360277.04;planendtime=1356360409.25;cases={'case1__2012-12-24__22.44.37': ['stopped', 1356360283.119, 1356360409.25, 'failed', 'Traceback (most recent call last):\n  File "C:\\workplace\\atplatform\\plan\\runengine\\exceptioncatch.py", line 12, in wrappedFunc\n    func(*arg,**argd)\n  File "C:\\workplace\\atplatform\\plan\\runengine\\execute.py", line 40, in exec_case\n    raise Exception(str(e),pic)\nException: (\'eeeeeeefffffffffffffff\', u\'C:\\\\workplace\\\\exceptionpic\\\\case1__2012-12-24__22.44.37_errortime_Mon Dec 24 22.46.47 2012.png\')\n', 'case1__2012-12-24__22.44.37_errortime_Mon Dec 24 22.46.47 2012.png']};plancases=[['case1', {'Webdriverhub': 'http://localhost:4444/wd/hub', 'Browserversion': '', 'Javascriptenabled': 'True', 'ignoreProtectedModeSettings':'True', 'Platform': 'WINDOWS', 'Browsername': 'chrome', 'Findtimeout': 10}]];