planname="progress4";sumofcases=3;planedtime=1357575671.55;planstarttime=1357575672.55;planendtime=1357575690.24;cases={'case_test2__2013-01-08__00.21.12': ['stopped', 1357575675.899, 1357575681.567, 'failed', 'Traceback (most recent call last):\n  File "C:\\workplace\\atplatform\\plan\\runengine\\exceptioncatch.py", line 11, in wrappedFunc\n    func(*arg,**argd)\n  File "C:\\workplace\\atplatform\\plan\\runengine\\execute.py", line 24, in exec_case\n    case.init()\n  File "C:\\workplace\\atplatform\\plan\\cases\\case_test2\\case_test2.py", line 25, in init\n    om.gWebelement()\n  File "C:\\workplace\\atplatform\\plan\\cases\\case_test2\\objectmapping.py", line 12, in gWebelement\n    unionmon_login_username_1_web_element=we(driver,"web_element",["partial_link_text","eeeeeeeeee"])\nNameError: global name \'we\' is not defined\n', ''], 'case_test3__2013-01-08__00.21.13': ['stopped', 1357575675.915, 1357575681.558, 'failed', 'Traceback (most recent call last):\n  File "C:\\workplace\\atplatform\\plan\\runengine\\exceptioncatch.py", line 11, in wrappedFunc\n    func(*arg,**argd)\n  File "C:\\workplace\\atplatform\\plan\\runengine\\execute.py", line 24, in exec_case\n    case.init()\n  File "C:\\workplace\\atplatform\\plan\\cases\\case_test3\\case_test3.py", line 25, in init\n    om.gWebelement()\n  File "C:\\workplace\\atplatform\\plan\\cases\\case_test3\\objectmapping.py", line 12, in gWebelement\n    unionmon_login_username_1_web_element=we(driver,"web_element",["partial_link_text","eeeeeeeeee"])\nNameError: global name \'we\' is not defined\n', ''], 'case_test1__2013-01-08__00.21.14': ['stopped', 1357575685.935, 1357575690.235, 'failed', 'Traceback (most recent call last):\n  File "C:\\workplace\\atplatform\\plan\\runengine\\exceptioncatch.py", line 11, in wrappedFunc\n    func(*arg,**argd)\n  File "C:\\workplace\\atplatform\\plan\\runengine\\execute.py", line 24, in exec_case\n    case.init()\n  File "C:\\workplace\\atplatform\\plan\\cases\\case_test1\\case_test1.py", line 25, in init\n    om.gWebelement()\n  File "C:\\workplace\\atplatform\\plan\\cases\\case_test1\\objectmapping.py", line 12, in gWebelement\n    unionmon_login_username_1_web_element=we(driver,"web_element",["partial_link_text","eeeeeeeeee"])\nNameError: global name \'we\' is not defined\n', '']};plancases=[['case_test2', {'Webdriverhub': 'http://localhost:4444/wd/hub', 'Browserversion': '', 'Javascriptenabled': 'True', 'ignoreProtectedModeSettings':'True', 'Platform': 'WINDOWS', 'Browsername': 'chrome', 'Findtimeout': 10}], ['case_test3', {'Webdriverhub': 'http://localhost:4444/wd/hub', 'Browserversion': '', 'Javascriptenabled': 'True', 'ignoreProtectedModeSettings':'True', 'Platform': 'WINDOWS', 'Browsername': 'chrome', 'Findtimeout': 10}], ['case_test1', {'Webdriverhub': 'http://localhost:4444/wd/hub', 'Browserversion': '', 'Javascriptenabled': 'True', 'ignoreProtectedModeSettings':'True', 'Platform': 'WINDOWS', 'Browsername': 'chrome', 'Findtimeout': 10}]];